### ISSUE TITLE
Verify schnorrkel vrf on EVM

### ISSUE THREAD

**Issue by h4x3rotab** [w3f/schnorrkel#83]
It is something possible? EVM has very limited instructions. It looks like even schnorr is not supported?

**Comment by burdges** [comment]
It's extremely painful, you'd could compile rust to EVM maybe but the gas would be astronomically expensive.  If you absolutely require this, then you could implement a SNARK verifier gadget, but then you'd need non-native curve arithmetic since EVM only supports SNARKs on BN254.  Ain't much going on in schnorkell, but this non-native curve arithmetic requires enough constraints your SNARK prover runs slow.

Ideally EVM will simply die one day.  :)
